version: "3"
#networks:
#  selenoid:
#    external:
#      name: selenoid # 需要事先创建：docker network create selenoid

#networks:
#  se-net:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.177.0.0/16

services:
  selenoid:
    container_name: selenoid
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "./config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./logs:/opt/selenoid/logs"
    command: [ "-conf", "/etc/selenoid/browsers.json",
               "-video-output-dir", "/opt/selenoid/video",
               "-log-output-dir", "/opt/selenoid/logs",
               "-limit", "10",
               "-disable-queue",
               "-container-network", "bridge" ]
    ports:
      - "4444:4444"
#    networks:
#      - selenoid

  selenoid-ui:
    network_mode: bridge
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
    ports:
      - "8081:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
#    networks:
#      - selenoid

  #  webapp:
  #    container_name: webapp
  #    image: rubyangxg/jd-qinglong:jar
  #    environment:
  #      - "SPRING_PROFILES_ACTIVE=docker"
  #    ports:
  #      - "5701:8080"
  #    volumes:
  #      - ./env.properties:/env.properties
  #    depends_on:
  #      - chrome
  #      - qinglong

#  qinglong1:
#    container_name: qinglong1
#    image: whyour/qinglong:latest
#    volumes:
#      - ./data/config:/ql/config
#      - ./data/log:/ql/log
#      - ./data/db:/ql/db
#      - ./data/scripts:/ql/scripts
#      - ./data/repo:/ql/repo
#      - ./data/raw:/ql/raw
#      - ./data/jbot:/ql/jbot
#    ports:
#      - "0.0.0.0:5700:5700"
#    environment:
#      - ENABLE_HANGUP=true
#      - ENABLE_WEB_PANEL=true
#    restart: always


